[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pymupdf>=1.26.3",
    "streamlit>=1.48.0",
]
